/**
 * Audio helpers: synthesize pronunciation, cache it as a blob, and play it.
 *
 * Synthesis goes through the inference router (local MMS first, OpenAI
 * fallback). Synthesized clips are cached in the blob store so the second
 * play is instant and offline.
 */

import { base } from '$app/paths';
import type { Language, ManabiSettings } from '$lib/db/types';
import { getBlobUrl, hasBlob, storeBlob } from '$lib/db/blob-store';
import { synthesize } from '$lib/inference/router';

// --- Prerecorded audio (static MP3s generated by tools/gen-audio.py) --------
// Generated offline with edge-tts; the manifest maps language → text → clip id.
// This is the primary audio path: it works with no in-browser TTS at all.

export type AudioManifest = Record<string, Record<string, string>>;
let manifestPromise: Promise<AudioManifest> | null = null;

/** Load (and cache) the prerecorded-audio manifest: language → text → clip id. */
export function loadAudioManifest(): Promise<AudioManifest> {
	if (!manifestPromise) {
		manifestPromise = fetch(`${base}/audio/manifest.json`)
			.then((r) => (r.ok ? r.json() : {}))
			.catch(() => ({}));
	}
	return manifestPromise;
}

/** Whether a prerecorded clip exists for this exact text (sync, given a manifest). */
export function hasPrerecorded(manifest: AudioManifest, language: Language, text: string): boolean {
	return !!manifest[language]?.[text.trim()];
}

/** URL of a prerecorded clip for this exact text, or null if none exists. */
export async function prerecordedUrl(language: Language, text: string): Promise<string | null> {
	const id = (await loadAudioManifest())[language]?.[text.trim()];
	return id ? `${base}/audio/${id}.mp3` : null;
}

/** Play a plain URL (e.g. a prerecorded clip). */
export async function playUrl(url: string): Promise<void> {
	await new Audio(url).play().catch(() => {});
}

/** Synthesize `text` and store the result, returning a `blob:` ref or null. */
export async function synthesizeToRef(
	text: string,
	language: Language,
	settings: ManabiSettings
): Promise<string | null> {
	const res = await synthesize({ text, language }, settings);
	if (!res.ok || !res.value) return null;
	const blob = new Blob([res.value.audio], { type: res.value.mimeType });
	return storeBlob(blob, res.value.mimeType);
}

/** Play a stored blob by ref. Resolves when playback starts (or no-ops). */
export async function playRef(ref: string): Promise<void> {
	const url = await getBlobUrl(ref);
	if (!url) return;
	const audio = new Audio(url);
	audio.addEventListener('ended', () => URL.revokeObjectURL(url));
	await audio.play().catch(() => URL.revokeObjectURL(url));
}

export { hasBlob };
