<script lang="ts">
	import '../app.css';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import {
		Home, GraduationCap, BookOpen, Table2, BookA, Library, LayoutGrid, BarChart3,
		Sparkles, Settings as SettingsIcon, Menu, X, Sun, Moon
	} from 'lucide-svelte';
	import { initDB, settings, updateSettings } from '$lib/db/store';

	let { children } = $props();
	let ready = $state(false);
	let drawerOpen = $state(false);

	const NAV = [
		{ href: '/', label: 'Home', icon: Home },
		{ href: '/review', label: 'Review', icon: GraduationCap },
		{ href: '/read', label: 'Read', icon: BookOpen },
		{ href: '/scripts', label: 'Scripts', icon: Table2 },
		{ href: '/vocab', label: 'Vocab', icon: BookA },
		{ href: '/items', label: 'Items', icon: Library },
		{ href: '/lessons', label: 'Lessons', icon: LayoutGrid },
		{ href: '/dashboard', label: 'Progress', icon: BarChart3 },
		{ href: '/workbench', label: 'Workbench', icon: Sparkles },
		{ href: '/settings', label: 'Settings', icon: SettingsIcon }
	];

	function applyTheme(theme: string) {
		const root = document.documentElement;
		root.classList.remove('light', 'dark');
		if (theme === 'light' || theme === 'dark') root.classList.add(theme);
	}
	$effect(() => {
		if (ready) applyTheme($settings.theme);
	});

	function prefersDark(): boolean {
		return typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches;
	}
	const isDark = $derived($settings.theme === 'dark' || ($settings.theme === 'system' && prefersDark()));
	function toggleTheme() {
		updateSettings({ theme: isDark ? 'light' : 'dark' });
	}

	const activePath = $derived($page.url.pathname);
	function isActive(href: string): boolean {
		return href === '/' ? activePath === '/' : activePath.startsWith(href);
	}

	// Close the mobile drawer whenever the route changes.
	$effect(() => {
		activePath;
		drawerOpen = false;
	});

	onMount(async () => {
		await initDB();
		ready = true;
		// Register the precaching service worker (generated by @vite-pwa). This
		// makes the app installable + the shell available offline. Fire-and-forget
		// so it never blocks boot; the SW self-updates (registerType autoUpdate).
		if ('serviceWorker' in navigator) {
			navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => {});
		}
	});
</script>

{#if !ready}
	<div class="boot">Loading Manabi…</div>
{:else}
	<!-- Mobile top bar -->
	<header class="topbar">
		<button class="icon-btn" onclick={() => (drawerOpen = !drawerOpen)} aria-label="Menu" aria-expanded={drawerOpen}>
			{#if drawerOpen}<X size={20} />{:else}<Menu size={20} />{/if}
		</button>
		<a href="/" class="tb-brand"><span class="logo">学</span><span class="name">Manabi</span></a>
		<button class="icon-btn" onclick={toggleTheme} aria-label="Toggle light/dark theme">
			{#if isDark}<Sun size={18} />{:else}<Moon size={18} />{/if}
		</button>
	</header>

	<div class="shell">
		<aside class="sidebar" class:open={drawerOpen}>
			<div class="brand">
				<span class="logo">学</span>
				<span class="name">Manabi</span>
			</div>

			<nav>
				{#each NAV as item (item.href)}
					<a href={item.href} class="nav-link" class:active={isActive(item.href)}>
						<item.icon size={18} />
						<span>{item.label}</span>
					</a>
				{/each}
			</nav>

			<button class="theme-row" onclick={toggleTheme}>
				{#if isDark}<Sun size={16} /> Light mode{:else}<Moon size={16} /> Dark mode{/if}
			</button>
		</aside>

		{#if drawerOpen}
			<button class="backdrop" onclick={() => (drawerOpen = false)} aria-label="Close menu"></button>
		{/if}

		<main class="content">
			{@render children?.()}
		</main>
	</div>
{/if}

<style>
	.boot {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100vh;
		color: var(--color-text-muted);
	}
	.shell {
		display: grid;
		grid-template-columns: 15rem 1fr;
		min-height: 100vh;
	}
	.sidebar {
		border-right: 1px solid var(--color-border);
		background: var(--color-bg-secondary);
		padding: 1.25rem 0.85rem;
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
		position: sticky;
		top: 0;
		height: 100vh;
	}
	.brand,
	.tb-brand {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		padding: 0 0.5rem;
		color: var(--color-text);
	}
	.logo {
		font-family: var(--font-script);
		font-size: 1.6rem;
		font-weight: 700;
		color: var(--color-accent);
	}
	.name {
		font-weight: 700;
		font-size: 1.15rem;
	}
	nav {
		display: flex;
		flex-direction: column;
		gap: 0.15rem;
	}
	.nav-link {
		display: flex;
		align-items: center;
		gap: 0.7rem;
		padding: 0.6rem 0.75rem;
		border-radius: 0.5rem;
		color: var(--color-text-muted);
		font-size: 0.95rem;
	}
	.nav-link:hover {
		background: var(--color-bg-elevated);
		color: var(--color-text);
	}
	.nav-link.active {
		background: var(--color-bg-elevated);
		color: var(--color-accent);
		font-weight: 600;
	}
	.theme-row {
		margin-top: auto;
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.6rem 0.75rem;
		border-radius: 0.5rem;
		border: 1px solid var(--color-border);
		background: var(--color-bg);
		color: var(--color-text-muted);
		font-size: 0.9rem;
	}
	.theme-row:hover {
		color: var(--color-accent);
		border-color: var(--color-accent);
	}
	.content {
		padding: 2rem 2.5rem;
		max-width: 64rem;
		width: 100%;
	}

	/* Top bar + icon buttons — hidden on desktop. */
	.topbar {
		display: none;
		align-items: center;
		gap: 0.5rem;
		/* Respect the notch / status bar when installed as a PWA. */
		padding: calc(0.5rem + env(safe-area-inset-top)) calc(0.75rem + env(safe-area-inset-right))
			0.5rem calc(0.75rem + env(safe-area-inset-left));
		border-bottom: 1px solid var(--color-border);
		background: var(--color-bg-secondary);
		position: sticky;
		top: 0;
		z-index: 30;
	}
	.icon-btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 2.4rem;
		height: 2.4rem;
		border-radius: 0.5rem;
		border: 1px solid transparent;
		background: transparent;
		color: var(--color-text);
		flex-shrink: 0;
	}
	.icon-btn:hover {
		background: var(--color-bg-elevated);
	}
	.backdrop {
		display: none;
	}

	@media (max-width: 820px) {
		.topbar {
			display: flex;
		}
		.tb-brand {
			flex: 1;
			padding-left: 0.25rem;
		}
		.tb-brand .name {
			font-size: 1.05rem;
		}

		.shell {
			display: block;
			min-height: auto;
		}
		.sidebar {
			position: fixed;
			top: 0;
			left: 0;
			bottom: 0;
			width: 15rem;
			height: 100dvh;
			z-index: 40;
			transform: translateX(-100%);
			transition: transform 0.2s ease;
			box-shadow: 0 0 2rem rgba(0, 0, 0, 0.3);
			/* Keep drawer nav clear of the notch / home indicator. */
			padding-top: calc(1.25rem + env(safe-area-inset-top));
			padding-bottom: calc(1.25rem + env(safe-area-inset-bottom));
			padding-left: calc(0.85rem + env(safe-area-inset-left));
		}
		.sidebar.open {
			transform: none;
		}
		/* In the mobile drawer the brand and theme toggle live in the top bar instead. */
		.sidebar .brand,
		.sidebar .theme-row {
			display: none;
		}
		.sidebar nav {
			margin-top: 0.5rem;
		}
		.backdrop {
			display: block;
			position: fixed;
			inset: 0;
			z-index: 35;
			border: none;
			background: rgba(0, 0, 0, 0.4);
		}
		.content {
			padding: 1.25rem calc(1rem + env(safe-area-inset-right))
				calc(1.25rem + env(safe-area-inset-bottom)) calc(1rem + env(safe-area-inset-left));
			max-width: 100%;
		}
	}
</style>
