<script lang="ts">
	import '../app.css';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { Settings as SettingsIcon, Sun, Moon } from 'lucide-svelte';
	import { initDB, settings, updateSettings } from '$lib/db/store';
	import { LANGUAGES } from '$lib/db/types';
	import { startAutoSync } from '$lib/sync';
	import { isNavActive, LIBRARY, PRIMARY } from '$lib/nav';
	import { immersive } from '$lib/ui';

	let { children } = $props();
	let ready = $state(false);

	function applyTheme(theme: string) {
		const root = document.documentElement;
		root.classList.remove('light', 'dark');
		if (theme === 'light' || theme === 'dark') root.classList.add(theme);
	}
	$effect(() => {
		if (ready) applyTheme($settings.theme);
	});

	function prefersDark(): boolean {
		return typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches;
	}
	const isDark = $derived($settings.theme === 'dark' || ($settings.theme === 'system' && prefersDark()));
	function toggleTheme() {
		updateSettings({ theme: isDark ? 'light' : 'dark' });
	}

	const activePath = $derived($page.url.pathname);
	const langNative = $derived(LANGUAGES.find((l) => l.code === $settings.activeLanguage)?.native ?? '');
	const sidebarPrimary = PRIMARY.filter((p) => p.href !== '/library');
	const settingsActive = $derived(isNavActive({ href: '/settings' }, activePath));

	onMount(async () => {
		await initDB();
		ready = true;
		// GitHub sync (if configured): pull/merge/push on start + when back online.
		void startAutoSync();
		// Register the precaching service worker (generated by @vite-pwa). This
		// makes the app installable + the shell available offline. Fire-and-forget
		// so it never blocks boot; the SW self-updates (registerType autoUpdate).
		if ('serviceWorker' in navigator) {
			navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => {});
		}
	});
</script>

{#if !ready}
	<div class="boot">Loading Manabi…</div>
{:else}
	<div class="app" class:immersive={$immersive}>
		<!-- Phone top bar: brand, active language, settings. -->
		<header class="topbar">
			<a href="/" class="tb-brand"><span class="logo">学</span><span class="name">Manabi</span></a>
			<a href="/" class="lang-chip" title="Switch language">{langNative}</a>
			<a href="/settings" class="icon-btn" class:active={settingsActive} aria-label="Settings">
				<SettingsIcon size={20} />
			</a>
		</header>

		<div class="shell">
			<!-- Desktop sidebar -->
			<aside class="sidebar">
				<div class="brand">
					<span class="logo">学</span>
					<span class="name">Manabi</span>
				</div>

				<nav class="side-nav" aria-label="Main">
					{#each sidebarPrimary as item (item.href)}
						<a href={item.href} class="nav-link" class:active={isNavActive(item, activePath)}>
							<item.icon size={18} />
							<span>{item.label}</span>
						</a>
					{/each}

					<a href="/library" class="nav-head" class:active={activePath === '/library'}>Library</a>
					{#each LIBRARY as item (item.href)}
						<a href={item.href} class="nav-link sub" class:active={isNavActive(item, activePath)}>
							<item.icon size={16} />
							<span>{item.label}</span>
						</a>
					{/each}
				</nav>

				<div class="side-foot">
					<a href="/settings" class="nav-link" class:active={settingsActive}>
						<SettingsIcon size={18} />
						<span>Settings</span>
					</a>
					<button class="theme-row" onclick={toggleTheme}>
						{#if isDark}<Sun size={16} /> Light mode{:else}<Moon size={16} /> Dark mode{/if}
					</button>
				</div>
			</aside>

			<main class="content">
				{@render children?.()}
			</main>
		</div>

		<!-- Phone bottom tab bar -->
		<nav class="tabbar" aria-label="Main">
			{#each PRIMARY as item (item.href)}
				{@const on = isNavActive(item, activePath)}
				<a href={item.href} class="tab" class:active={on} aria-current={on ? 'page' : undefined}>
					<span class="ic"><item.icon size={22} /></span>
					<span class="tab-label">{item.label}</span>
				</a>
			{/each}
		</nav>
	</div>
{/if}

<style>
	.boot {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100vh;
		color: var(--color-text-muted);
	}
	.shell {
		display: grid;
		grid-template-columns: 15rem 1fr;
		min-height: 100vh;
	}
	.sidebar {
		border-right: 1px solid var(--color-border);
		background: var(--color-bg-secondary);
		padding: 1.25rem 0.85rem;
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
		position: sticky;
		top: 0;
		height: 100vh;
	}
	.brand,
	.tb-brand {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		padding: 0 0.5rem;
		color: var(--color-text);
	}
	.logo {
		font-family: var(--font-script);
		font-size: 1.6rem;
		font-weight: 700;
		color: var(--color-accent);
	}
	.name {
		font-weight: 700;
		font-size: 1.15rem;
	}
	.side-nav {
		display: flex;
		flex-direction: column;
		gap: 0.15rem;
	}
	.nav-link {
		display: flex;
		align-items: center;
		gap: 0.7rem;
		padding: 0.6rem 0.75rem;
		border-radius: 0.5rem;
		color: var(--color-text-muted);
		font-size: 0.95rem;
	}
	.nav-link.sub {
		padding: 0.45rem 0.75rem 0.45rem 1rem;
		font-size: 0.9rem;
	}
	.nav-link:hover {
		background: var(--color-bg-elevated);
		color: var(--color-text);
	}
	.nav-link.active {
		background: var(--color-bg-elevated);
		color: var(--color-accent);
		font-weight: 600;
	}
	.nav-head {
		margin: 0.9rem 0 0.2rem;
		padding: 0 0.75rem;
		font-size: 0.72rem;
		font-weight: 700;
		letter-spacing: 0.08em;
		text-transform: uppercase;
		color: var(--color-text-muted);
	}
	.nav-head:hover,
	.nav-head.active {
		color: var(--color-accent);
	}
	.side-foot {
		margin-top: auto;
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}
	.theme-row {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.6rem 0.75rem;
		border-radius: 0.5rem;
		border: 1px solid var(--color-border);
		background: var(--color-bg);
		color: var(--color-text-muted);
		font-size: 0.9rem;
	}
	.theme-row:hover {
		color: var(--color-accent);
		border-color: var(--color-accent);
	}
	.content {
		padding: 2rem 2.5rem;
		max-width: 64rem;
		width: 100%;
	}

	/* Phone chrome — hidden on desktop. */
	.topbar,
	.tabbar {
		display: none;
	}
	.icon-btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 2.4rem;
		height: 2.4rem;
		border-radius: 0.5rem;
		color: var(--color-text);
		flex-shrink: 0;
	}
	.icon-btn.active {
		color: var(--color-accent);
		background: var(--color-bg-elevated);
	}
	.lang-chip {
		font-family: var(--font-script);
		font-size: 0.9rem;
		font-weight: 600;
		color: var(--color-accent);
		padding: 0.25rem 0.6rem;
		border-radius: 999px;
		background: color-mix(in srgb, var(--color-accent) 12%, transparent);
	}

	@media (max-width: 820px) {
		.topbar {
			display: flex;
			align-items: center;
			gap: 0.5rem;
			/* Respect the notch / status bar when installed as a PWA. */
			padding: calc(0.4rem + env(safe-area-inset-top)) calc(0.6rem + env(safe-area-inset-right))
				0.4rem calc(0.9rem + env(safe-area-inset-left));
			border-bottom: 1px solid var(--color-border);
			background: var(--color-bg-secondary);
			position: sticky;
			top: 0;
			z-index: 30;
		}
		.tb-brand {
			flex: 1;
			padding-left: 0;
		}
		.tb-brand .name {
			font-size: 1.05rem;
		}

		.shell {
			display: block;
			min-height: auto;
		}
		.sidebar {
			display: none;
		}
		.content {
			padding: 1.25rem calc(1rem + env(safe-area-inset-right))
				calc(var(--tabbar-h) + env(safe-area-inset-bottom) + 1.5rem) calc(1rem + env(safe-area-inset-left));
			max-width: 100%;
		}

		.tabbar {
			display: grid;
			grid-template-columns: repeat(5, 1fr);
			position: fixed;
			left: 0;
			right: 0;
			bottom: 0;
			height: calc(var(--tabbar-h) + env(safe-area-inset-bottom));
			padding: 0 env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
			background: var(--color-bg-secondary);
			border-top: 1px solid var(--color-border);
			z-index: 30;
		}
		.tab {
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			gap: 0.2rem;
			color: var(--color-text-muted);
			font-size: 0.68rem;
			font-weight: 500;
			-webkit-tap-highlight-color: transparent;
		}
		.tab .ic {
			display: inline-flex;
			padding: 0.2rem 0.9rem;
			border-radius: 999px;
			transition: background 0.15s ease;
		}
		.tab.active {
			color: var(--color-accent);
			font-weight: 700;
		}
		.tab.active .ic {
			background: color-mix(in srgb, var(--color-accent) 16%, transparent);
		}

		/* Focus mode: a running review session owns the whole screen. */
		.immersive .topbar,
		.immersive .tabbar {
			display: none;
		}
		.immersive .content {
			padding-top: calc(0.75rem + env(safe-area-inset-top));
			padding-bottom: calc(1.25rem + env(safe-area-inset-bottom));
		}
	}
</style>
